PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE `careers_responsibilities` (
  	`_order` integer NOT NULL,
  	`_parent_id` integer NOT NULL,
  	`id` text PRIMARY KEY NOT NULL,
  	`text` text,
  	FOREIGN KEY (`_parent_id`) REFERENCES `careers`(`id`) ON UPDATE no action ON DELETE cascade
  );
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(0,3,'seed-resp-creative-video-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Theo dõi mục tiêu vị trí và biến kế hoạch thành kết quả thực tế theo từng tuần.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(0,4,'seed-resp-customer-service-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Theo dõi mục tiêu vị trí và biến kế hoạch thành kết quả thực tế theo từng tuần.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(0,6,'seed-resp-fulfillment-full-time-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Theo dõi mục tiêu vị trí và biến kế hoạch thành kết quả thực tế theo từng tuần.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(0,5,'seed-resp-human-resource-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Theo dõi mục tiêu vị trí và biến kế hoạch thành kết quả thực tế theo từng tuần.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(0,2,'seed-resp-marketing-facebook-ads-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Theo dõi mục tiêu vị trí và biến kế hoạch thành kết quả thực tế theo từng tuần.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(0,1,'seed-resp-marketing-google-ads-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Theo dõi mục tiêu vị trí và biến kế hoạch thành kết quả thực tế theo từng tuần.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(0,7,'seed-resp-van-hanh-san-etsy-intern-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Theo dõi mục tiêu vị trí và biến kế hoạch thành kết quả thực tế theo từng tuần.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,3,'seed-resp-creative-video-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Phối hợp với các team liên quan để vận hành chiến dịch e-commerce quốc tế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,4,'seed-resp-customer-service-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Phối hợp với các team liên quan để vận hành chiến dịch e-commerce quốc tế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,6,'seed-resp-fulfillment-full-time-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Phối hợp với các team liên quan để vận hành chiến dịch e-commerce quốc tế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,5,'seed-resp-human-resource-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Phối hợp với các team liên quan để vận hành chiến dịch e-commerce quốc tế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,2,'seed-resp-marketing-facebook-ads-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Phối hợp với các team liên quan để vận hành chiến dịch e-commerce quốc tế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,1,'seed-resp-marketing-google-ads-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Phối hợp với các team liên quan để vận hành chiến dịch e-commerce quốc tế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,7,'seed-resp-van-hanh-san-etsy-intern-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Phối hợp với các team liên quan để vận hành chiến dịch e-commerce quốc tế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(2,3,'seed-resp-creative-video-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Chủ động phân tích dữ liệu, phát hiện vấn đề và đề xuất cách tối ưu.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(2,4,'seed-resp-customer-service-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Chủ động phân tích dữ liệu, phát hiện vấn đề và đề xuất cách tối ưu.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(2,6,'seed-resp-fulfillment-full-time-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Chủ động phân tích dữ liệu, phát hiện vấn đề và đề xuất cách tối ưu.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(2,5,'seed-resp-human-resource-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Chủ động phân tích dữ liệu, phát hiện vấn đề và đề xuất cách tối ưu.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(2,2,'seed-resp-marketing-facebook-ads-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Chủ động phân tích dữ liệu, phát hiện vấn đề và đề xuất cách tối ưu.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(2,1,'seed-resp-marketing-google-ads-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Chủ động phân tích dữ liệu, phát hiện vấn đề và đề xuất cách tối ưu.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(2,7,'seed-resp-van-hanh-san-etsy-intern-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Chủ động phân tích dữ liệu, phát hiện vấn đề và đề xuất cách tối ưu.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,8,'6a27884535954f752e494dc4','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"- Tối ưu toàn bộ funnel chuyển đổi trên website: theo dõi hành vi, phân tích drop-off, đề xuất cải tiến. - Lên kế hoạch và triển khai A/B testing: layout, UX flow, copywrite, visual triggers… - Phối hợp với team thiết kế để tối ưu UI/UX, bảo đảm hiệu ứng thị giác thúc đẩy hành động (CTA clarity – visual hierarchy). - Viết micro-copy & conversion copy cho landing pages, onboarding flow, CRM touchpoints. - Theo dõi các chỉ số cốt lõi (CR,AOV, LTV, bounce rate…), rút insight và đề xuất chiến lược tăng trưởng. - Đóng góp vào roadmap cải thiện chuyển đổi dài hạn: từ web, CRM đến loyalty và referral. - Xây dựng và vận hành loyalty platform (tier benefits, reward logic, engagement loop). - Thực hiện các công việc khác theo yêu cầu của quản lý. ","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(2,8,'6a27887035954f752e494dc6','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"- Thực hiện các công việc khác theo yêu cầu của quản lý. ","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_responsibilities" ("_order","_parent_id","id","text") VALUES(1,11,'6a27d876bf5af030db9f98fe','{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}');
CREATE TABLE `careers_requirements` (
  	`_order` integer NOT NULL,
  	`_parent_id` integer NOT NULL,
  	`id` text PRIMARY KEY NOT NULL,
  	`text` text,
  	FOREIGN KEY (`_parent_id`) REFERENCES `careers`(`id`) ON UPDATE no action ON DELETE cascade
  );
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(0,3,'seed-req-creative-video-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Có tư duy ownership, giao tiếp rõ ràng và thích môi trường tăng trưởng nhanh.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(0,4,'seed-req-customer-service-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Có tư duy ownership, giao tiếp rõ ràng và thích môi trường tăng trưởng nhanh.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(0,6,'seed-req-fulfillment-full-time-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Có tư duy ownership, giao tiếp rõ ràng và thích môi trường tăng trưởng nhanh.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(0,5,'seed-req-human-resource-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Có tư duy ownership, giao tiếp rõ ràng và thích môi trường tăng trưởng nhanh.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(0,2,'seed-req-marketing-facebook-ads-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Có tư duy ownership, giao tiếp rõ ràng và thích môi trường tăng trưởng nhanh.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(0,1,'seed-req-marketing-google-ads-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Có tư duy ownership, giao tiếp rõ ràng và thích môi trường tăng trưởng nhanh.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(0,7,'seed-req-van-hanh-san-etsy-intern-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Có tư duy ownership, giao tiếp rõ ràng và thích môi trường tăng trưởng nhanh.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,3,'seed-req-creative-video-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Biết ưu tiên công việc, theo sát deadline và phối hợp tốt với đồng đội.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,4,'seed-req-customer-service-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Biết ưu tiên công việc, theo sát deadline và phối hợp tốt với đồng đội.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,6,'seed-req-fulfillment-full-time-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Biết ưu tiên công việc, theo sát deadline và phối hợp tốt với đồng đội.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,5,'seed-req-human-resource-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Biết ưu tiên công việc, theo sát deadline và phối hợp tốt với đồng đội.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,2,'seed-req-marketing-facebook-ads-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Biết ưu tiên công việc, theo sát deadline và phối hợp tốt với đồng đội.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,1,'seed-req-marketing-google-ads-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Biết ưu tiên công việc, theo sát deadline và phối hợp tốt với đồng đội.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,7,'seed-req-van-hanh-san-etsy-intern-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Biết ưu tiên công việc, theo sát deadline và phối hợp tốt với đồng đội.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(2,3,'seed-req-creative-video-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Kinh nghiệm liên quan đến e-commerce, POD hoặc marketplace là lợi thế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(2,4,'seed-req-customer-service-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Kinh nghiệm liên quan đến e-commerce, POD hoặc marketplace là lợi thế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(2,6,'seed-req-fulfillment-full-time-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Kinh nghiệm liên quan đến e-commerce, POD hoặc marketplace là lợi thế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(2,5,'seed-req-human-resource-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Kinh nghiệm liên quan đến e-commerce, POD hoặc marketplace là lợi thế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(2,2,'seed-req-marketing-facebook-ads-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Kinh nghiệm liên quan đến e-commerce, POD hoặc marketplace là lợi thế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(2,1,'seed-req-marketing-google-ads-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Kinh nghiệm liên quan đến e-commerce, POD hoặc marketplace là lợi thế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(2,7,'seed-req-van-hanh-san-etsy-intern-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Kinh nghiệm liên quan đến e-commerce, POD hoặc marketplace là lợi thế.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,8,'6a27887935954f752e494dc7','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_requirements" ("_order","_parent_id","id","text") VALUES(1,11,'6a27d87bbf5af030db9f98ff','{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}');
CREATE TABLE `careers_benefits` (
  	`_order` integer NOT NULL,
  	`_parent_id` integer NOT NULL,
  	`id` text PRIMARY KEY NOT NULL,
  	`text` text,
  	FOREIGN KEY (`_parent_id`) REFERENCES `careers`(`id`) ON UPDATE no action ON DELETE cascade
  );
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(0,3,'seed-benefit-creative-video-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Môi trường trẻ, tốc độ cao và nhiều cơ hội học từ các bài toán scale thật.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(0,4,'seed-benefit-customer-service-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Môi trường trẻ, tốc độ cao và nhiều cơ hội học từ các bài toán scale thật.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(0,6,'seed-benefit-fulfillment-full-time-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Môi trường trẻ, tốc độ cao và nhiều cơ hội học từ các bài toán scale thật.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(0,5,'seed-benefit-human-resource-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Môi trường trẻ, tốc độ cao và nhiều cơ hội học từ các bài toán scale thật.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(0,2,'seed-benefit-marketing-facebook-ads-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Môi trường trẻ, tốc độ cao và nhiều cơ hội học từ các bài toán scale thật.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(0,1,'seed-benefit-marketing-google-ads-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Môi trường trẻ, tốc độ cao và nhiều cơ hội học từ các bài toán scale thật.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(0,7,'seed-benefit-van-hanh-san-etsy-intern-1','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Môi trường trẻ, tốc độ cao và nhiều cơ hội học từ các bài toán scale thật.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,3,'seed-benefit-creative-video-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Được tham gia hệ thống e-commerce toàn cầu với quy trình và công cụ rõ ràng.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,4,'seed-benefit-customer-service-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Được tham gia hệ thống e-commerce toàn cầu với quy trình và công cụ rõ ràng.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,6,'seed-benefit-fulfillment-full-time-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Được tham gia hệ thống e-commerce toàn cầu với quy trình và công cụ rõ ràng.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,5,'seed-benefit-human-resource-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Được tham gia hệ thống e-commerce toàn cầu với quy trình và công cụ rõ ràng.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,2,'seed-benefit-marketing-facebook-ads-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Được tham gia hệ thống e-commerce toàn cầu với quy trình và công cụ rõ ràng.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,1,'seed-benefit-marketing-google-ads-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Được tham gia hệ thống e-commerce toàn cầu với quy trình và công cụ rõ ràng.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,7,'seed-benefit-van-hanh-san-etsy-intern-2','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Được tham gia hệ thống e-commerce toàn cầu với quy trình và công cụ rõ ràng.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(2,3,'seed-benefit-creative-video-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Review hiệu suất định kỳ, lương thưởng theo năng lực và hoạt động nội bộ.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(2,4,'seed-benefit-customer-service-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Review hiệu suất định kỳ, lương thưởng theo năng lực và hoạt động nội bộ.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(2,6,'seed-benefit-fulfillment-full-time-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Review hiệu suất định kỳ, lương thưởng theo năng lực và hoạt động nội bộ.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(2,5,'seed-benefit-human-resource-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Review hiệu suất định kỳ, lương thưởng theo năng lực và hoạt động nội bộ.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(2,2,'seed-benefit-marketing-facebook-ads-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Review hiệu suất định kỳ, lương thưởng theo năng lực và hoạt động nội bộ.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(2,1,'seed-benefit-marketing-google-ads-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Review hiệu suất định kỳ, lương thưởng theo năng lực và hoạt động nội bộ.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(2,7,'seed-benefit-van-hanh-san-etsy-intern-3','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Review hiệu suất định kỳ, lương thưởng theo năng lực và hoạt động nội bộ.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,8,'6a27888235954f752e494dc8','{"root":{"type":"root","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"paragraph","format":"","indent":0,"version":1,"direction":null,"children":[{"type":"text","text":"Thu nhập: - Thu nhập: 8-12 triệu + Bonus (theo performance) - Thời gian thử việc: 2 tháng (85% lương chính thức) - Review lương 2 lần/ năm  Phúc lợi khác: - Đóng BHXH, BHYT, BHTN theo quy định khi là nhân viên chính thức. - Lương tháng 13, thưởng lễ, Tết và các hoạt động nội bộ như happy hours, KICK-OFF theo quý. - Môi trường làm việc năng động, sáng tạo và thân thiện. - Cơ hội học hỏi, phát triển kỹ năng và lộ trình thăng tiến rõ ràng. - Chi tiết các quyền lợi sẽ được trao đổi cụ thể trong quá trình phỏng vấn.","detail":0,"format":0,"mode":"normal","style":"","version":1}]}]}}');
INSERT INTO "careers_benefits" ("_order","_parent_id","id","text") VALUES(1,11,'6a27d886bf5af030db9f9900','{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Thu nhập: - Thu nhập: 8-12 triệu + Bonus (theo performance) - Thời gian thử việc: 2 tháng (85% lương chính thức) - Review lương 2 lần/ năm  Phúc lợi khác: - Đóng BHXH, BHYT, BHTN theo quy định khi là nhân viên chính thức. - Lương tháng 13, thưởng lễ, Tết và các hoạt động nội bộ như happy hours, KICK-OFF theo quý. - Môi trường làm việc năng động, sáng tạo và thân thiện. - Cơ hội học hỏi, phát triển kỹ năng và lộ trình thăng tiến rõ ràng. - Chi tiết các quyền lợi sẽ được trao đổi cụ thể trong quá trình phỏng vấn.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}');
CREATE TABLE `careers` (
  	`id` integer PRIMARY KEY NOT NULL,
  	`title` text,
  	`slug` text,
  	`status` text DEFAULT 'draft',
  	`tag` text DEFAULT 'hiring',
  	`published_at` text,
  	`date_label` text DEFAULT '2026',
  	`department` text DEFAULT 'Thương mại điện tử',
  	`employment_type` text DEFAULT 'Toàn thời gian',
  	`location` text DEFAULT 'St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh',
  	`quantity` text DEFAULT '01',
  	`excerpt` text,
  	`lark_url` text,
  	`apply_url` text DEFAULT 'mailto:tuyendung@gobe.asia',
  	`description` text,
  	`working_time` text DEFAULT '8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',
  	`notes` text,
  	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
  	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
  	`_status` text DEFAULT 'draft'
  );
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(1,'Marketing Google Ads Toàn thời gian','marketing-google-ads','published','marketing','2025-12-08T00:00:00.000Z','08 Th12','Marketing hiệu suất','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Tối ưu chiến dịch Google Ads, đọc tín hiệu thị trường và scale sản phẩm e-commerce quốc tế.','https://gobe.asia/tuyen-dung-marketing-google-ads-full-time/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20MARKETING%20GOOGLE%20ADS%5D%20Ho%20va%20ten','Vai trò dành cho người thích test nhanh, đo dữ liệu rõ ràng và tối ưu tăng trưởng theo hiệu suất.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(2,'Marketing Facebook Ads Toàn thời gian','marketing-facebook-ads','published','marketing','2025-12-08T00:00:00.000Z','08 Th12','Marketing hiệu suất','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Triển khai, phân tích và scale chiến dịch Facebook Ads cho thị trường quốc tế.','https://gobe.asia/tuyen-dung-marketing-facebook-ads-full-time/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20MARKETING%20FACEBOOK%20ADS%5D%20Ho%20va%20ten','Bạn sẽ phối hợp với creative và vận hành để tìm angle bán hàng, tối ưu funnel và cải thiện hiệu quả quảng cáo.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(3,'Sáng tạo Video','creative-video','published','creative','2025-12-08T00:00:00.000Z','08 Th12','Sáng tạo','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Sản xuất video ngắn, visual angle và nội dung sáng tạo phục vụ chiến dịch e-commerce.','https://gobe.asia/tuyen-dung-creative-video-full-time/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20CREATIVE%20VIDEO%5D%20Ho%20va%20ten','Vai trò dành cho người có mắt nhìn visual, biết biến insight thành video ngắn có khả năng tạo chuyển đổi.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(4,'Chăm sóc khách hàng Toàn thời gian','customer-service','published','customerService','2025-01-05T00:00:00.000Z','05 Th1','Chăm sóc khách hàng','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Chăm sóc khách hàng, xử lý phản hồi và phối hợp vận hành để trải nghiệm mua hàng mượt mà.','https://gobe.asia/tuyen-dung-customer-service-full-time/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20CUSTOMER%20SERVICE%5D%20Ho%20va%20ten','Vị trí kết nối trực tiếp với khách hàng và team vận hành để xử lý phản hồi nhanh, rõ ràng, đúng quy trình.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(5,'Nhân sự Toàn thời gian','human-resource','published','humanResource','2025-08-29T00:00:00.000Z','29 Th8','Nhân sự','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Tuyển dụng, phát triển con người và xây dựng văn hóa vận hành chủ động trong đội ngũ.','https://gobe.asia/tuyen-dung-human-resource/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20HUMAN%20RESOURCE%5D%20Ho%20va%20ten','Vai trò hỗ trợ tuyển dụng, trải nghiệm nhân sự và văn hóa nội bộ trong môi trường tăng trưởng nhanh.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(6,'Fulfillment Toàn thời gian','fulfillment-full-time','published','operations','2025-04-21T00:00:00.000Z','21 Th4','Vận hành','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','02','Quản lý đơn hàng, điều phối supplier, logistics và theo dõi vận hành từ lúc nhận đơn đến khi giao thành công.','https://gobe.asia/tuyen-dung-fulfillment-full-time-3/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20FULFILLMENT%20FULL-TIME%5D%20Ho%20va%20ten','GoBeyond đang tìm kiếm nhân viên Fulfillment tài năng và nhiệt huyết để gia nhập đội ngũ vận hành e-commerce toàn cầu.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(7,'Thực tập Vận hành sàn Etsy','van-hanh-san-etsy-intern','published','internship','2025-04-21T00:00:00.000Z','21 Th4','Vận hành marketplace','Thực tập','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Thực tập vận hành sàn Etsy, hỗ trợ listing, tracking và quy trình xử lý dữ liệu sản phẩm.','https://gobe.asia/3250-2/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20ETSY%20OPERATIONS%20INTERN%5D%20Ho%20va%20ten','Vị trí thực tập dành cho người muốn học cách vận hành marketplace, xử lý listing và hỗ trợ dữ liệu sản phẩm.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(8,'CONVERSION RATE OPTIMIZATION (CRO)','conversion','published','marketing','2026-06-09T03:29:22.382Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,'https://gobeasia.sg.larksuite.com/wiki/NXK0wyZirihLVUkGBTlltJUngDe','mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, Từ thứ 2 đến thứ 6, Sáng thứ 7 remote. Nghỉ trưa: 12:00-13:30.',NULL,'2026-06-09T03:33:10.587Z','2026-06-09T03:27:07.126Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(9,'aa','aa','draft','hiring','2026-06-09T08:54:02.882Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T08:54:02.882Z','2026-06-09T08:53:47.633Z','published');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(10,NULL,NULL,'draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T08:54:10.288Z','2026-06-09T08:54:10.288Z','draft');
INSERT INTO "careers" ("id","title","slug","status","tag","published_at","date_label","department","employment_type","location","quantity","excerpt","lark_url","apply_url","description","working_time","notes","updated_at","created_at","_status") VALUES(11,'test bài đăng','test-bai-ang','published','hiring','2026-06-09T09:11:01.573Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T09:11:01.573Z','2026-06-09T09:04:57.235Z','published');
CREATE TABLE `_careers_v_version_responsibilities` (
  	`_order` integer NOT NULL,
  	`_parent_id` integer NOT NULL,
  	`id` integer PRIMARY KEY NOT NULL,
  	`text` text,
  	`_uuid` text,
  	FOREIGN KEY (`_parent_id`) REFERENCES `_careers_v`(`id`) ON UPDATE no action ON DELETE cascade
  );
INSERT INTO "_careers_v_version_responsibilities" ("_order","_parent_id","id","text","_uuid") VALUES(1,21,29,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d876bf5af030db9f98fe');
INSERT INTO "_careers_v_version_responsibilities" ("_order","_parent_id","id","text","_uuid") VALUES(1,22,30,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d876bf5af030db9f98fe');
INSERT INTO "_careers_v_version_responsibilities" ("_order","_parent_id","id","text","_uuid") VALUES(1,23,31,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d876bf5af030db9f98fe');
CREATE TABLE `_careers_v_version_requirements` (
  	`_order` integer NOT NULL,
  	`_parent_id` integer NOT NULL,
  	`id` integer PRIMARY KEY NOT NULL,
  	`text` text,
  	`_uuid` text,
  	FOREIGN KEY (`_parent_id`) REFERENCES `_careers_v`(`id`) ON UPDATE no action ON DELETE cascade
  );
INSERT INTO "_careers_v_version_requirements" ("_order","_parent_id","id","text","_uuid") VALUES(1,21,25,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d87bbf5af030db9f98ff');
INSERT INTO "_careers_v_version_requirements" ("_order","_parent_id","id","text","_uuid") VALUES(1,22,26,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d87bbf5af030db9f98ff');
INSERT INTO "_careers_v_version_requirements" ("_order","_parent_id","id","text","_uuid") VALUES(1,23,27,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Kỹ năng/ Chuyên môn - Tốt nghiệp Đại học chuyên ngành Marketing, Thương mại điện tử, Kinh doanh hoặc các ngành liên quan.  - Có từ 1 năm kinh nghiệm ở vị trí CRO, E-commerce Optimization, UX/Data Analyst hoặc các vị trí liên quan.  - Có kinh nghiệm làm việc với Claude code hoặc claude design - Có kinh nghiệm làm product page , landing page : Funnelish, Gempage, custom HTML ,  - Hiểu rõ funnel chuyển đổi, hành vi người dùng trên website và các chỉ số liên quan đến conversion.  - Có kinh nghiệm làm việc với UI/UX, A/B testing hoặc tối ưu conversion trong môi trường E-commerce.  - Thành thạo các công cụ phân tích như GA4, Hotjar/Clarity hoặc các công cụ tương đương.  - Có tư duy phân tích dữ liệu, khả năng đọc insight và đề xuất phương án cải thiện hiệu quả.  - Điểm cộng:   - Có hiểu biết về copywriting phục vụ chuyển đổi (CTA, micro-copy, offer framing…).    - Biết sử dụng các công cụ chỉnh sửa prototype như Figma/FigJam/Canva là lợi thế.    - Có kinh nghiệm trong lĩnh vực POD, E-commerce US, CRM, loyalty hoặc retention là lợi thế. Thái độ/Giá trị - Chủ động, ham học hỏi, có tinh thần nghiên cứu và liên tục cải tiến. - Có tư duy logic, khả năng giải quyết vấn đề và xử lý tình huống linh hoạt. - Kỹ năng giao tiếp rõ ràng, phối hợp tốt với các bộ phận liên quan. - Cẩn thận, trách nhiệm, có khả năng làm việc độc lập và làm việc nhóm hiệu quả.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d87bbf5af030db9f98ff');
CREATE TABLE `_careers_v_version_benefits` (
  	`_order` integer NOT NULL,
  	`_parent_id` integer NOT NULL,
  	`id` integer PRIMARY KEY NOT NULL,
  	`text` text,
  	`_uuid` text,
  	FOREIGN KEY (`_parent_id`) REFERENCES `_careers_v`(`id`) ON UPDATE no action ON DELETE cascade
  );
INSERT INTO "_careers_v_version_benefits" ("_order","_parent_id","id","text","_uuid") VALUES(1,21,26,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Thu nhập: - Thu nhập: 8-12 triệu + Bonus (theo performance) - Thời gian thử việc: 2 tháng (85% lương chính thức) - Review lương 2 lần/ năm  Phúc lợi khác: - Đóng BHXH, BHYT, BHTN theo quy định khi là nhân viên chính thức. - Lương tháng 13, thưởng lễ, Tết và các hoạt động nội bộ như happy hours, KICK-OFF theo quý. - Môi trường làm việc năng động, sáng tạo và thân thiện. - Cơ hội học hỏi, phát triển kỹ năng và lộ trình thăng tiến rõ ràng. - Chi tiết các quyền lợi sẽ được trao đổi cụ thể trong quá trình phỏng vấn.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d886bf5af030db9f9900');
INSERT INTO "_careers_v_version_benefits" ("_order","_parent_id","id","text","_uuid") VALUES(1,22,27,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Thu nhập: - Thu nhập: 8-12 triệu + Bonus (theo performance) - Thời gian thử việc: 2 tháng (85% lương chính thức) - Review lương 2 lần/ năm  Phúc lợi khác: - Đóng BHXH, BHYT, BHTN theo quy định khi là nhân viên chính thức. - Lương tháng 13, thưởng lễ, Tết và các hoạt động nội bộ như happy hours, KICK-OFF theo quý. - Môi trường làm việc năng động, sáng tạo và thân thiện. - Cơ hội học hỏi, phát triển kỹ năng và lộ trình thăng tiến rõ ràng. - Chi tiết các quyền lợi sẽ được trao đổi cụ thể trong quá trình phỏng vấn.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d886bf5af030db9f9900');
INSERT INTO "_careers_v_version_benefits" ("_order","_parent_id","id","text","_uuid") VALUES(1,23,28,'{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Thu nhập: - Thu nhập: 8-12 triệu + Bonus (theo performance) - Thời gian thử việc: 2 tháng (85% lương chính thức) - Review lương 2 lần/ năm  Phúc lợi khác: - Đóng BHXH, BHYT, BHTN theo quy định khi là nhân viên chính thức. - Lương tháng 13, thưởng lễ, Tết và các hoạt động nội bộ như happy hours, KICK-OFF theo quý. - Môi trường làm việc năng động, sáng tạo và thân thiện. - Cơ hội học hỏi, phát triển kỹ năng và lộ trình thăng tiến rõ ràng. - Chi tiết các quyền lợi sẽ được trao đổi cụ thể trong quá trình phỏng vấn.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""}],"direction":null,"format":"","indent":0,"type":"root","version":1}}','6a27d886bf5af030db9f9900');
CREATE TABLE `_careers_v` (
  	`id` integer PRIMARY KEY NOT NULL,
  	`parent_id` integer,
  	`version_title` text,
  	`version_slug` text,
  	`version_status` text DEFAULT 'draft',
  	`version_tag` text DEFAULT 'hiring',
  	`version_published_at` text,
  	`version_date_label` text DEFAULT '2026',
  	`version_department` text DEFAULT 'Thương mại điện tử',
  	`version_employment_type` text DEFAULT 'Toàn thời gian',
  	`version_location` text DEFAULT 'St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh',
  	`version_quantity` text DEFAULT '01',
  	`version_excerpt` text,
  	`version_lark_url` text,
  	`version_apply_url` text DEFAULT 'mailto:tuyendung@gobe.asia',
  	`version_description` text,
  	`version_working_time` text DEFAULT '8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',
  	`version_notes` text,
  	`version_updated_at` text,
  	`version_created_at` text,
  	`version__status` text DEFAULT 'draft',
  	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
  	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
  	`snapshot` integer,
  	`published_locale` text,
  	`latest` integer,
  	`autosave` integer,
  	FOREIGN KEY (`parent_id`) REFERENCES `careers`(`id`) ON UPDATE no action ON DELETE set null
  );
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(1,NULL,NULL,NULL,'draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-06T15:37:01.526Z','2026-06-06T15:37:01.526Z','draft','2026-06-06T15:37:01.561Z','2026-06-06T15:37:01.561Z',NULL,NULL,0,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(2,NULL,'TUYỂN DỤNG MARKETING GOOGLE ADS FULL-TIME','tuyen-dung-marketing-google-ads-full-time','draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','TUYỂN DỤNG MARKETING GOOGLE ADS FULL-TIME','TUYỂN DỤNG MARKETING GOOGLE ADS FULL-TIME','mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-06T15:39:44.539Z','2026-06-06T15:37:01.526Z','draft','2026-06-06T15:37:39.893Z','2026-06-06T15:39:44.539Z',NULL,NULL,0,1);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(3,NULL,'TUYỂN DỤNG MARKETING GOOGLE ADS FULL-TIME','tuyen-dung-marketing-google-ads-full-time','draft','hiring','2026-06-06T15:39:47.071Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','TUYỂN DỤNG MARKETING GOOGLE ADS FULL-TIME','TUYỂN DỤNG MARKETING GOOGLE ADS FULL-TIME','mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-06T15:39:47.071Z','2026-06-06T15:37:01.526Z','published','2026-06-06T15:39:47.155Z','2026-06-06T15:39:47.155Z',NULL,NULL,0,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(4,1,'Marketing Google Ads Toàn thời gian','marketing-google-ads','published','marketing','2025-12-08T00:00:00.000Z','08 Th12','Marketing hiệu suất','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Tối ưu chiến dịch Google Ads, đọc tín hiệu thị trường và scale sản phẩm e-commerce quốc tế.','https://gobe.asia/tuyen-dung-marketing-google-ads-full-time/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20MARKETING%20GOOGLE%20ADS%5D%20Ho%20va%20ten','Vai trò dành cho người thích test nhanh, đo dữ liệu rõ ràng và tối ưu tăng trưởng theo hiệu suất.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z',NULL,NULL,1,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(5,2,'Marketing Facebook Ads Toàn thời gian','marketing-facebook-ads','published','marketing','2025-12-08T00:00:00.000Z','08 Th12','Marketing hiệu suất','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Triển khai, phân tích và scale chiến dịch Facebook Ads cho thị trường quốc tế.','https://gobe.asia/tuyen-dung-marketing-facebook-ads-full-time/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20MARKETING%20FACEBOOK%20ADS%5D%20Ho%20va%20ten','Bạn sẽ phối hợp với creative và vận hành để tìm angle bán hàng, tối ưu funnel và cải thiện hiệu quả quảng cáo.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z',NULL,NULL,1,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(6,3,'Sáng tạo Video','creative-video','published','creative','2025-12-08T00:00:00.000Z','08 Th12','Sáng tạo','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Sản xuất video ngắn, visual angle và nội dung sáng tạo phục vụ chiến dịch e-commerce.','https://gobe.asia/tuyen-dung-creative-video-full-time/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20CREATIVE%20VIDEO%5D%20Ho%20va%20ten','Vai trò dành cho người có mắt nhìn visual, biết biến insight thành video ngắn có khả năng tạo chuyển đổi.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z',NULL,NULL,1,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(7,4,'Chăm sóc khách hàng Toàn thời gian','customer-service','published','customerService','2025-01-05T00:00:00.000Z','05 Th1','Chăm sóc khách hàng','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Chăm sóc khách hàng, xử lý phản hồi và phối hợp vận hành để trải nghiệm mua hàng mượt mà.','https://gobe.asia/tuyen-dung-customer-service-full-time/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20CUSTOMER%20SERVICE%5D%20Ho%20va%20ten','Vị trí kết nối trực tiếp với khách hàng và team vận hành để xử lý phản hồi nhanh, rõ ràng, đúng quy trình.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z',NULL,NULL,1,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(8,5,'Nhân sự Toàn thời gian','human-resource','published','humanResource','2025-08-29T00:00:00.000Z','29 Th8','Nhân sự','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Tuyển dụng, phát triển con người và xây dựng văn hóa vận hành chủ động trong đội ngũ.','https://gobe.asia/tuyen-dung-human-resource/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20HUMAN%20RESOURCE%5D%20Ho%20va%20ten','Vai trò hỗ trợ tuyển dụng, trải nghiệm nhân sự và văn hóa nội bộ trong môi trường tăng trưởng nhanh.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z',NULL,NULL,1,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(9,6,'Fulfillment Toàn thời gian','fulfillment-full-time','published','operations','2025-04-21T00:00:00.000Z','21 Th4','Vận hành','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','02','Quản lý đơn hàng, điều phối supplier, logistics và theo dõi vận hành từ lúc nhận đơn đến khi giao thành công.','https://gobe.asia/tuyen-dung-fulfillment-full-time-3/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20FULFILLMENT%20FULL-TIME%5D%20Ho%20va%20ten','GoBeyond đang tìm kiếm nhân viên Fulfillment tài năng và nhiệt huyết để gia nhập đội ngũ vận hành e-commerce toàn cầu.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z',NULL,NULL,1,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(10,7,'Thực tập Vận hành sàn Etsy','van-hanh-san-etsy-intern','published','internship','2025-04-21T00:00:00.000Z','21 Th4','Vận hành marketplace','Thực tập','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01','Thực tập vận hành sàn Etsy, hỗ trợ listing, tracking và quy trình xử lý dữ liệu sản phẩm.','https://gobe.asia/3250-2/','mailto:tuyendung@gobe.asia?subject=%5BGOBEYOND%20-%20ETSY%20OPERATIONS%20INTERN%5D%20Ho%20va%20ten','Vị trí thực tập dành cho người muốn học cách vận hành marketplace, xử lý listing và hỗ trợ dữ liệu sản phẩm.','8:00-17:30, từ thứ 2 đến thứ 6, thứ 7 remote. Nghỉ trưa: 12:00-13:30.','Seed từ website cũ gobe.asia/tuyen-dung/','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z','published','2026-06-07T17:21:00.305Z','2026-06-07T17:21:00.305Z',NULL,NULL,1,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(11,8,NULL,NULL,'draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T03:27:07.126Z','2026-06-09T03:27:07.126Z','draft','2026-06-09T03:27:07.243Z','2026-06-09T03:27:07.243Z',NULL,NULL,0,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(12,8,'CONVERSION RATE OPTIMIZATION (CRO)','conversion','published','marketing','2026-06-09T03:29:22.382Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,'https://gobeasia.sg.larksuite.com/wiki/NXK0wyZirihLVUkGBTlltJUngDe','mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, Từ thứ 2 đến thứ 6, Sáng thứ 7 remote. Nghỉ trưa: 12:00-13:30.',NULL,'2026-06-09T03:32:59.574Z','2026-06-09T03:27:07.126Z','draft','2026-06-09T03:27:43.932Z','2026-06-09T03:32:59.574Z',NULL,NULL,0,1);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(13,8,'CONVERSION RATE OPTIMIZATION (CRO)','conversion','published','marketing','2026-06-09T03:29:22.382Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,'https://gobeasia.sg.larksuite.com/wiki/NXK0wyZirihLVUkGBTlltJUngDe','mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, Từ thứ 2 đến thứ 6, Sáng thứ 7 remote. Nghỉ trưa: 12:00-13:30.',NULL,'2026-06-09T03:33:10.587Z','2026-06-09T03:27:07.126Z','published','2026-06-09T03:33:10.690Z','2026-06-09T03:33:10.690Z',NULL,NULL,0,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(14,8,'CONVERSION RATE OPTIMIZATION (CRO)','conversion','published','marketing','2026-06-09T03:29:22.382Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,'https://gobeasia.sg.larksuite.com/wiki/NXK0wyZirihLVUkGBTlltJUngDe','mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, Từ thứ 2 đến thứ 6, Sáng thứ 7 remote. Nghỉ trưa: 12:00-13:30.',NULL,'2026-06-09T04:26:49.434Z','2026-06-09T03:27:07.126Z','draft','2026-06-09T04:26:49.434Z','2026-06-09T04:26:49.434Z',NULL,NULL,1,1);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(15,9,NULL,NULL,'draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T08:53:47.633Z','2026-06-09T08:53:47.633Z','draft','2026-06-09T08:53:47.765Z','2026-06-09T08:53:47.765Z',NULL,NULL,0,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(16,9,'aa','aa','draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T08:53:57.459Z','2026-06-09T08:53:47.633Z','draft','2026-06-09T08:53:57.459Z','2026-06-09T08:53:57.459Z',NULL,NULL,0,1);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(17,9,'aa','aa','draft','hiring','2026-06-09T08:54:02.882Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T08:54:02.882Z','2026-06-09T08:53:47.633Z','published','2026-06-09T08:54:03.121Z','2026-06-09T08:54:03.121Z',NULL,NULL,1,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(18,10,NULL,NULL,'draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T08:54:10.288Z','2026-06-09T08:54:10.288Z','draft','2026-06-09T08:54:10.396Z','2026-06-09T08:54:10.396Z',NULL,NULL,0,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(19,10,NULL,NULL,'draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T08:54:27.819Z','2026-06-09T08:54:10.288Z','draft','2026-06-09T08:54:27.819Z','2026-06-09T08:54:27.819Z',NULL,NULL,1,1);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(20,11,NULL,NULL,'draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T09:04:57.235Z','2026-06-09T09:04:57.235Z','draft','2026-06-09T09:04:57.412Z','2026-06-09T09:04:57.412Z',NULL,NULL,0,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(21,11,'test bài đăng','test-bai-ang','draft','hiring',NULL,'2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T09:10:57.778Z','2026-06-09T09:04:57.235Z','draft','2026-06-09T09:10:11.001Z','2026-06-09T09:10:57.778Z',NULL,NULL,0,1);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(22,11,'test bài đăng','test-bai-ang','published','hiring','2026-06-09T09:11:01.573Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T09:11:01.573Z','2026-06-09T09:04:57.235Z','published','2026-06-09T09:11:01.710Z','2026-06-09T09:11:01.710Z',NULL,NULL,0,0);
INSERT INTO "_careers_v" ("id","parent_id","version_title","version_slug","version_status","version_tag","version_published_at","version_date_label","version_department","version_employment_type","version_location","version_quantity","version_excerpt","version_lark_url","version_apply_url","version_description","version_working_time","version_notes","version_updated_at","version_created_at","version__status","created_at","updated_at","snapshot","published_locale","latest","autosave") VALUES(23,11,'test bài đăng','test-bai-ang','published','hiring','2026-06-09T09:11:01.573Z','2026','Thương mại điện tử','Toàn thời gian','St Moritz, 1014 Đường Phạm Văn Đồng, TP. Hồ Chí Minh','01',NULL,NULL,'mailto:tuyendung@gobe.asia',NULL,'8:00-17:30, tu thu 2 den thu 6, thu 7 remote. Nghi trua: 12:00-13:30.',NULL,'2026-06-09T09:21:39.857Z','2026-06-09T09:04:57.235Z','draft','2026-06-09T09:18:05.960Z','2026-06-09T09:21:39.857Z',NULL,NULL,1,1);
